# Generated by Django 4.1.13 on 2025-05-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('s3_url', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('title', 'autor')},
            },
        ),
        migrations.CreateModel(
            name='VideoDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('s3_url', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stat1', models.CharField(max_length=3)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('original_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
            options={
                'unique_together': {('title', 'autor')},
            },
        ),
    ]
