# Generated by Django 4.1.13 on 2025-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='s3_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='videodetectionresult',
            name='s3_url',
            field=models.URLField(max_length=500),
        ),
    ]
