# Generated by Django 4.1.13 on 2025-05-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_video_id_alter_video_s3_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
    ]
