# Generated by Django 4.1.13 on 2025-05-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='public_url',
            field=models.URLField(default='https://s3-us-west-2.amazonaws.com', max_length=500),
        ),
    ]
