# Generated by Django 4.1.13 on 2025-05-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_video_public_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodetectionresult',
            name='stat1',
        ),
    ]
