# Generated by Django 4.1.13 on 2025-05-15 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_videodetectionresult_stat1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_box_loss', models.FloatField(blank=True, null=True)),
                ('train_cls_loss', models.FloatField(blank=True, null=True)),
                ('train_dfl_loss', models.FloatField(blank=True, null=True)),
                ('val_box_loss', models.FloatField(blank=True, null=True)),
                ('val_cls_loss', models.FloatField(blank=True, null=True)),
                ('val_dfl_loss', models.FloatField(blank=True, null=True)),
                ('val_precision', models.FloatField(blank=True, null=True)),
                ('val_recall', models.FloatField(blank=True, null=True)),
                ('val_map50', models.FloatField(blank=True, null=True)),
                ('val_map50_95', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iou_threshold', models.FloatField()),
                ('max_age', models.PositiveIntegerField()),
                ('min_hits', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='avg_confidence',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='avg_people_per_frame',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='confidence_threshold',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='detections_discarded',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='detections_per_frame',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='frame_processed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='frames_with_detections',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='peak_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='peak_frame_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='people_detected',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='person_presence_percent',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='processing_time_seconds',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='time_per_person',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='total_detections',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='video_duration',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='video_fps',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('metrics', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_model', to='api.modelmetrics')),
            ],
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='ml_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.mlmodel'),
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='tracker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tracker'),
        ),
    ]
