# Generated by Django 4.1.13 on 2025-05-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_modelmetrics_tracker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetectionresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
