# Generated by Django 4.1.13 on 2025-05-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_videodetectionresult_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
    ]
