# Generated by Django 4.1.13 on 2025-05-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_video_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videodetectionresult',
            unique_together={('title', 'autor', 'ml_model')},
        ),
    ]
