# Generated by Django 4.1.13 on 2025-05-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_videodetectionresult_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='public_url',
        ),
        migrations.AddField(
            model_name='videodetectionresult',
            name='public_url',
            field=models.URLField(default='https://s3-us-west-2.amazonaws.com', max_length=500),
        ),
    ]
