# Generated by Django 4.1.13 on 2025-05-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_video_public_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodetectionresult',
            name='uploaded_at',
        ),
    ]
